name: "CQHTTPMirai"
author: "yyuueexxiinngg"
version: "0.2.4-SNAPSHOT-1.0-M4-dev"
vcs: "https://github.com/yyuueexxiinngg/cqhttp-mirai"
main: "tech.mihoyo.mirai.PluginBase"
info: "Mirai to CoolQ HTTP API Plugin"
depends: []